### ISSUE TITLE
Working for Arduino IDE

### ISSUE THREAD

**Issue by gabiknight** [Hex2424/esp32_deauth_patch#1]
Firstly, THANK YOU! This works perfectly, I know this must have taken several hours, but your hard work has beaten the tyranny that wants to cut off our liberty. 

I tested on Arduino IDE using ESP32. Depending on which one exists on your computer and the board version you selected, the path where the patch should be paste is:

- C:\Users\[user]\Documents\ArduinoData\packages\esp32\hardware\esp32\[2.0.10 or 2.0.11]\tools\sdk\esp32\lib
- C:\Users\[user]\AppData\Local\Arduino15\packages\esp32\hardware\esp32\[2.0.10 or 2.0.11]\tools\sdk\esp32\lib

Tested successfully on ESP32 board version 2.0.10 and 2.0.11.

The terminal shows the following message, but the deauth function actually works.

![image](https://github.com/Hex2424/esp32_deauth_patch/assets/39223734/26a1353f-d79d-4500-9492-ce85e8a5831f)

**Comment by Hex2424** [comment]
Hello, so to make it clear, I provided wrong path in Readme right and wrong message (it was for fun :D)? And you are welcome, if facing any issues, please tell me, because it was working for me, but not sure if everyone else having same experience, ESP32 take from people knife to make them not stab everyone else even so knife is used not just for killing, so it is some freedom limitation agree on you
